name: Snyk Testing

on: push

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Install Snyk CLI and snyk-to-html
        run: |
          npm install -g snyk snyk-to-html

      - name: Run Snyk and generate HTML report
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test --json | snyk-to-html -o snyk-report.html

      - name: Save Snyk HTML Report as Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: snyk-html-report
          path: snyk-report.html
